---
title: "Garage Climate Stats"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dygraphs)
library(xts)
df <- read.csv("~/Documents/Programming/RaspberryPi/garage/garage.txt", header = TRUE, 
                     stringsAsFactors = FALSE, 
                     colClasses =  c("character", "numeric", "numeric", "numeric", "numeric"), skipNul = TRUE)
df <- df[-c(1:11, 2052:2069), ]
rownames(df) <- 1:nrow(df)
df$date <- paste(df$date, ":00", sep = "")
#df$diff <- c(0,diff(as.POSIXct(df$date)))
#df.blackout <- df[sort(c(as.integer(rownames(df[df$diff > 15, ])), as.integer(rownames(df[df$diff > 15, ])) - 1)), ]
#df.blackout$date <- as.POSIXct(df.blackout$date)
```

Temperature {data-orientation=rows data-icon="ion-thermometer"}
=======================================================================

Row
-----------------------------------------------------------------------

```{r}
temp <- df[,1:3]
temp$temp.avg <- round(rowMeans(temp[,2:3]), 2)

# tdy <- as.Date(final.temp[nrow(final.temp), 1])
# ydy <- tdy - 1
# ydy.idx <- grep(ydy, final.temp$date)
# ydy.df <- final.temp[ydy.idx, ]
```

### Min Temp
```{r}
gauge(round(min(temp$temp.avg)), min = 40, max = 80, symbol = '°', gaugeSectors(
  success = c(65, 80), warning = c(40, 65),
  colors = c("#d6604d", "#4393c3")
))
```

### Avg Temp
```{r}
gauge(round(mean(temp$temp.avg)), min = 40, max = 80, symbol = '°', gaugeSectors(
  success = c(65, 80), warning = c(40, 65),
  colors = c("#d6604d", "#4393c3")
))
```

### Max Temp
```{r}
gauge(round(max(temp$temp.avg)), min = 40, max = 80, symbol = '°', gaugeSectors(
  success = c(65, 80), warning = c(40, 65),
  colors = c("#d6604d", "#4393c3")
))
```

Row
-----------------------------------------------------------------------

###  Temperature (15 min. intervals, 12/22/16 - 01/12/17) 


```{r}
temp.ts.obj <- xts(temp[,2:4], order.by = as.POSIXct(temp$date, format = "%Y-%m-%d %H:%M:%S"))

dygraph(temp.ts.obj) %>% 
  dySeries(c("temp.pres", "temp.avg", "temp"), label = "Avg. Temp", color = "purple") %>%
  dyAxis("y", label = "Temperature (F)") %>% 
  #dyShading(from = "2017-01-12", to = "2017-01-12", color = "#A8A8A8") %>% 
  dyLegend(show = "always", hideOnMouseOut = TRUE, width = 400) %>% 
  dyRangeSelector()
```

> `r paste("Last update:", df$date[nrow(df)])`

Pressure {data-icon="ion-ios-timer-outline"}
=======================================================================
Column
-----------------------------------------------------------------------

###  Pressure (15 min. intervals, 12/22/16 - 01/12/17)

```{r}
pres <- df[,c(1,4)]
pres.ts.obj <- xts(pres[, 2, drop = FALSE], order.by = as.POSIXct(pres$date, format = "%Y-%m-%d %H:%M:%S"))

dygraph(pres.ts.obj) %>% 
  dySeries("pres", label = "Pressure", color = "orange") %>% 
  dyAxis("y", label = "Pressure (mb)") %>% 
  dyLegend(show = "always", hideOnMouseOut = TRUE, width = 400) %>% 
  dyRangeSelector()
```

Humidity {data-icon="ion-waterdrop"}
=======================================================================

Column
-----------------------------------------------------------------------

### Humidity (15 min. intervals, 12/22/16 - 01/12/17)

```{r}
humd <- df[, c(1,5)]
humd.ts.obj <- xts(humd[, 2, drop = FALSE], order.by = as.POSIXct(humd$date, format = "%Y-%m-%d %H:%M:%S"))

dygraph(humd.ts.obj) %>% 
  dySeries("humd", label = "Humidity", color = "blue") %>% 
  dyAxis("y", label = "Humidity (%)") %>% 
  dyLegend(show = "always", hideOnMouseOut = TRUE, width = 400) %>% 
  dyRangeSelector()
```

